### ISSUE TITLE
Media keys on Mac

### ISSUE THREAD

**Issue by bhaap** [tmk/tmk_keyboard#195] opened 2015-03-04 15:56 UTC
The KC_MNXT and KC_MPRV does not work on Mac, The MPLY works thou, have i missed that this is intended and there is another code for mac media keys?

**Comment by tmk** [comment] 2015-03-06 22:17
hm, I don't have Mac nor idea on this.

I think you may be able to know what keycodes you can use on mac by skiming the sources around here.
https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-606.1.7/IOHIDFamily

**Comment by tmk** [comment] 2015-03-07 05:04
Hm, looks to me like those keys sould work.

`kHIDUsage_Csmr_ScanNextTrack`  and  `kHIDUsage_Csmr_ScanPreviousTrack` handled in `IOHIDConsumer::dispatchConsumerEvent` are `KC_MNXT` and `KC_MPRV` in TMK.

https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-606.1.7/IOHIDFamily/IOHIDConsumer.cpp

**Comment by bhaap** [comment] 2015-03-08 07:27
When running usb overdrive it recognizes the next track button on my keyboard as a different next track button then on the internal keyboard, wonder if there is 2 almost identical codes for next track. Do you know of any program that can see what scancodes that im sending with the internal keyboard for mac?

**Comment by tmk** [comment] 2015-03-08 08:15
I don't know how to get scancode on OS X. But from reading source codes I guess USB Apple Keyboard sends F6 or F8 as normal keycode and Fn in Apple vendor specific usage page.

What do you mean with "internal keyboard" actually? Macbook builtin keyboard?
And I don't know much about how Mac media keys work. Fn+F6=previous track and Fn+F8=next track, right?

**Comment by bhaap** [comment] 2015-03-08 08:31
Yeah the internal keyboard on my laptop :) f7 and f9 is prev and next. i could be like that

**Comment by bhaap** [comment] 2015-03-08 09:55
But the config in systemprefs only works on the built in keyboard not on my tmk one even thou it has a fn layer

**Comment by tmk** [comment] 2015-03-08 10:13
Fn key on tmk is completely different from Mac. It doesn't send any key code basically. Mac mediakey functions on macbook and apple keyboard are vendor specific unfortunately, systempref works only for apple hardware.

But as I said previously Mac seems to support standard HID media control codes too. Tmk can send only the standard codes.

To me weird thing here is why MPLY only works.

Any other Mac user here? can you confirm this problem?

**Comment by bhaap** [comment] 2015-03-08 10:20
The mnxt and mprv do work with itunes i just noticed, but not with spotify or vlc.

**Comment by tmk** [comment] 2015-03-08 10:24
Interesting.
I'll look into OSX sources again later. It may handle apple media key and standard one as different key events.

**Comment by bhaap** [comment] 2015-03-08 10:28
If you want any help just tell me, im not that good with programming but I can troubleshoot for you if you want to :D

**Comment by kairyu** [comment] 2015-03-08 10:38
Do you have tried this #160 ?

**Comment by bhaap** [comment] 2015-03-08 10:41
I have not will try it

**Comment by tmk** [comment] 2015-03-09 11:19
Thanks, kairyu.
Oops, this issue is exactly same as that. It was not so long ago, I blame my short memory :D 

>The "Play/Pause"(KC_MPLY) works good on Apple OS. But "Next/Prev Track" buttons are unfunctional.
Apple OS use "Fast Forwad"(F9 on Apple keyboard) & "Rewind"(F7 on Apple keyboard) instead.

bhaap, close this issue if it works for you.

**Comment by tmk** [comment] 2015-03-09 11:35
Added FAQ entry.
https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#media-control-keys-in-mac-osx

**Comment by bhaap** [comment] 2015-03-09 11:37
The MFFD and MRWD does not work for me. Not in itunes nor in spotify.

**Comment by tmk** [comment] 2015-03-09 11:41
Oh, shame.
We need other Mac users's help then.

**Comment by bhaap** [comment] 2015-03-09 11:53
The MNXT and MPRV do work as i said with itunes, but for some reason it doesnt work with Spotify and other 3rd party apps. Very wierd.

**Comment by bhaap** [comment] 2015-03-11 09:02
Got this from a mac programmer:
"They go through the OS (as in: they trigger events that applications can see), but they aren't delivered as keyboard events. They're system-defined events. So the very concept of key codes doesn't apply to them.

The easiest way to capture them without having iTunes interfere is setting up an event tap for NX_SYSDEFINED/NSSystemDefined events. From there, one way to identify individual media keys is converting the tapped CGEvent to an NSEvent and looking at the NSEvent's -data1."

**Comment by kyleboyle** [comment] 2015-05-09 13:00
I am also having this issue. MNXT and MPRV don't do anything system wide (spotify, vlc etc), and the PR #160 that implements MFFD and MRWD also don't do anything, I would say that PR doesn't solve any issues. I'm happy to help as my ergodox won't be acceptable as my daily driver until I can control media on OSX.

**Comment by tmk** [comment] 2015-05-09 14:42
You need this Fix too.

https://github.com/tmk/tmk_keyboard/pull/199

**Comment by tmk** [comment] 2015-07-03 21:01
https://geekhack.org/index.php?topic=71702.msg1789509#msg1789509
Confirmed.


On Mac just use `KC_MFFD`(`KC_MEDIA_FAST_FORWARD`) and `KC_MRWD`(`KC_MEDIA_REWIND`) instead of KC_ and KC_MNXT and KC_MPRV.

All fixes were already merged in my TMK repository you don't need any patch for this.

For Ergodox version(https://github.com/cub-uanic/tmk_keyboard) you need to apply two patches.
https://github.com/cub-uanic/tmk_keyboard/issues/22

**Closed by tmk** 2015-07-03 21:01 UTC

**Comment by tmk** [comment] 2015-11-04 23:11
TODO: 
add description in keymap document

**Comment by tmk** [comment] 2016-01-11 15:46
Added this to FAQ.

https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#media-control-keys-in-mac-osx

**Comment by unrealhoang** [comment] 2016-03-28 09:47
I'm currently using OSX El Capitan (10.11.3), MNXT & MPRV are working correctly but MPLY is not working at all.

**Comment by tmk** [comment] 2016-03-28 12:23
Huh, confusing as hell. Ditch OSX or give up those keys.

**Comment by kaansoral** [comment] 2016-03-28 14:44
I've been using TMK on OSX for months, MPLY worked for me all this time, didn't have any issues at any point

**Comment by unrealhoang** [comment] 2016-03-28 14:57
hmm, my current keymap: 
```
#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* 0: qwerty */
    KEYMAP_ANSI(
        ESC, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, BSPC, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSLS, \
        LCTL,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,     ENT,  \
        LSFT,Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,          RSFT, \
        FN0,LALT,LGUI,          SPC,                     RGUI, FN0, APP, CAPS),
    KEYMAP_ANSI(
        GRV, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, DEL,  \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,VOLD,VOLU,MUTE, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,LEFT,DOWN,UP,  RGHT,TRNS,TRNS,     TRNS, \
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,MPLY,MPRV,MNXT,          MSEL, \
        TRNS,TRNS,TRNS,          TRNS,                    TRNS,TRNS,TRNS,SLCK),
};
const uint16_t PROGMEM fn_actions[] = {
    /* Poker Layout */
    [0] = ACTION_LAYER_MOMENTARY(1),  // to Fn overlay
};
```

MPRV & MNXT works but not MPLY, am I doing anything wrong?

**Comment by kaansoral** [comment] 2016-03-28 17:10
I can't see anything wrong, it triggers, plays, pauses iTunes, or VLC for me, whichever is active

The only possible difference is that I'm using a 4-5 months old firmware, yet I don't think that would make a difference, correct me If I'm wrong

**Comment by Nephiel** [comment] 2016-03-28 18:54
I'm having the same issue on Linux with a build from yesterday.  
- MPRV and MNXT work fine
- MPLY and MSTP do not even send anything at all (xev reports nothing)  

On my previous build (from January 17th) they were all working.

**Comment by Nephiel** [comment] 2016-03-28 20:23
I've looked into this, it's a regression of #199 from commit 5e9b21d77d71bede3fbcbefd7567af22f3b0d153.  
The enum for media control consumer key codes in `keycode.h` got reordered in that commit. Since `keymap.c` only reads the enum from `AUDIO_MUTE` to `MEDIA_REWIND`, the following keys are ignored:
- `MEDIA_STOP`
- `MEDIA_PLAY_PAUSE`
- `MEDIA_EJECT`
- `MEDIA_SELECT`
- `MAIL`
- `CALCULATOR`
- `MY_COMPUTER`
- `WWW_SEARCH`
- `WWW_HOME`
- `WWW_BACK`
- `WWW_FORWARD`
- `WWW_STOP`
- `WWW_REFRESH`
- `WWW_FAVORITES`  

Possible fixes are: restoring the order of the enum, placing `MEDIA_REWIND` at the end, or reverting keymap.c from #199.

**Comment by unrealhoang** [comment] 2016-03-28 20:31
@Nephiel Awesome, It works now. Thank you for taking time investigating this issue

**Comment by tmk** [comment] 2016-03-28 22:06
aaargh, I broke it at the commit 5e9b21d. OSX is not guilty this time lol.
This commit will fix it.
https://github.com/tmk/tmk_keyboard/commit/24cee117d0abe1e8ba9a136f6908f10c30a11bb9
